version: '3.9'
services:
    build-sys:
        image: monius/build-system-ubuntu:personal
        env_file: .env
        network_mode: host
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        devices:
            - "/dev/net/tun:/dev/net/tun"